# Generated by Django 5.0.2 on 2024-03-04 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('release_date', models.DateField(verbose_name='Дата выпуска')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='NetworkNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('email', models.EmailField(help_text='Введите действующий email', max_length=254, verbose_name='Email')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('house_number', models.CharField(max_length=20, verbose_name='Номер дома')),
                ('node_type', models.CharField(choices=[('Factory', 'Завод'), ('RetailNetwork', 'Розничная сеть'), ('IndividualEntrepreneur', 'Индивидуальный предприниматель')], max_length=50, verbose_name='Тип')),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Долг поставщику')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='trading_platform.networknode', verbose_name='Поставщик')),
                ('products', models.ManyToManyField(related_name='network_nodes', to='trading_platform.product', verbose_name='Продукты')),
            ],
            options={
                'verbose_name': 'Звено',
                'verbose_name_plural': 'Звенья',
            },
        ),
    ]
