# Generated by Django 5.0.2 on 2024-03-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_platform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='networknode',
            name='level',
            field=models.IntegerField(default=0, max_length=3, verbose_name='Уровень в торговой сети'),
            preserve_default=False,
        ),
    ]
