# Generated by Django 5.0.2 on 2024-03-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_platform', '0002_networknode_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networknode',
            name='level',
            field=models.IntegerField(verbose_name='Уровень в торговой сети'),
        ),
    ]
